version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123456 
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports: 
      - 5432:5432
  adminer:
    image: adminer
    ports: 
      - 8080:8080

networks:
  default:

volumes:
  postgres:
    driver: local
